### ISSUE TITLE
http://localhost:9200/_reloadikdict?reload=1 not working now...

### ISSUE THREAD

**Issue by icedfish** [wyhw/elasticsearch-analysis-ik-reload-dict#1]
{"error":"NoSuchMethodError[org.wltea.analyzer.dic.Dictionary.reloadDictionary()V]","status":500}

**Comment by wyhw** [comment]
昏，分词没换？

**Comment by wyhw** [comment]
好了。要换分词  

Requirement

elasticsearch-analysis-ik source for this fix:

Reload IK dictionary fix 

get jar package:

wget -O elasticsearch-analysis-ik-1.2.6.jar http://github.com/wyhw/elasticsearch-analysis-ik/blob/master/elasticsearch-analysis-ik-1.2.6.jar?raw=true --no-check-certificate
