### ISSUE TITLE
elasticsearch-analysis-ik-1.3.2.jar 是从基于哪个版本修改的啊？

### ISSUE THREAD

**Issue by wellpeng** [wyhw/elasticsearch-analysis-ik-reload-dict#2]
elasticsearch-analysis-ik-1.3.2.jar 是从基于哪个版本修改的啊？目前 @medcl 那里的最高到 1.2.8

**Comment by wyhw** [comment]
@medcl 的最新修改支持 1.3.2。 1.3.2 你可以从我的分支中拿出。

2014-09-25 11:03 GMT+08:00 well notifications@github.com:

> elasticsearch-analysis-ik-1.3.2.jar 是从基于哪个版本修改的啊？目前 @medcl
> https://github.com/medcl 哪里的最高到 1.2.8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wyhw/elasticsearch-analysis-ik-reload-dict/issues/2.

## 

## 

Best Regards,

王卫华 Wyhw
百姓网www.baixing.com
世界500强eBay全球成员

FAX:021-52589825
Mob:13917067724
E-mail:wangweihua@baixing.com wangweihua@baixing.com
MSN:wyhw2002@hotmail.com

**Comment by wyhw** [comment]
https://github.com/wyhw/elasticsearch-analysis-ik

**Comment by wellpeng** [comment]
感谢 @wyhw 的回复。
1.2.7 | 1.2.1
我目前使用的是 1.2.1 版本的 es，也就是说我需要下载你修改后的对应的 1.2.7 版本，是吗？还是 1.2.1 也可以使用 1.3.2 这个版本的插件？

**Comment by wyhw** [comment]
https://github.com/wyhw/elasticsearch-analysis-ik/blob/056aaed194f7235ce1d3f2ac3d9575ecf721f22e/elasticsearch-analysis-ik-1.2.6.jar

在 2014年9月25日 下午1:46，well notifications@github.com写道：

> 感谢 @wyhw https://github.com/wyhw 的回复。
> 1.2.7 | 1.2.1
> 我目前使用的是 1.2.1 版本的 es，也就是说我需要下载你修改后的对应的 1.2.7 版本，是吗？还是 1.2.1 也可以使用 1.3.2
> 这个版本的插件？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wyhw/elasticsearch-analysis-ik-reload-dict/issues/2#issuecomment-56776277
> .

## 

## 

Best Regards,

王卫华 Wyhw
百姓网www.baixing.com
世界500强eBay全球成员

FAX:021-52589825
Mob:13917067724
E-mail:wangweihua@baixing.com wangweihua@baixing.com
MSN:wyhw2002@hotmail.com
